############################################################
# +------------------------------------------------------+ #
# |             BanterFreedomMod: Remastered             | #
# |                      plugin.yml                      | #
# +------------------------------------------------------+ #
############################################################

name: BanterFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: Remastered
description: Plugin for a FreedomServer!
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI, Spigot, Votifier]
authors: [TFM_DEV, FOP_DEV, RF_DEV, BF_DEV, __Crafted]

