############################################################
# +------------------------------------------------------+ #
# |             BanterFreedomMod: Remastered             | #
# |                      plugin.yml                      | #
# +------------------------------------------------------+ #
############################################################

name: BanterFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: Remastered
description: Plugin for a FreedomServer!
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI, Spigot, Votifier]
authors: [__Crafted]

